
Vagrant.configure("2") do |config|
 
  config.vm.box = "centos/7"

  #Mentioning the SSH Username/Password:
  # config.ssh.username="vagrant"
  # config.ssh.password="vagrant"

  #being configuring
  config.vm.define "lamp" do|lamp|

  #settingup hoostname/natwork
  lamp.vm.hostname="lamp"
  lamp.vm.network "private_network", ip: "192.168.205.10"
  lamp.vm.provision :shell, path: "vagrant.bootstrap.sh" #provisioning with script.sh
end

# End configuring
end